export enum ESignalRActionType {
    CONNECTING = 'connecting',
    CONNECTED = 'connected',
    DISCONNECT = 'disconnect',
    ERROR = 'error',
}

export enum ESignalRConnectionError {
    NO_ACCESS_TOKEN = 'No access token',
    CONNECTION_CLOSED = 'Connection closed',
    RECONNECTING = 'Reconnecting...',
}

export enum ESignalRError {
    CONNECTION_NOT_ESTABLISHED = 'Connection not established',
}

export enum ESignalEvent  {
    ADD_NEW_BACKUP = "ADD_NEW_BACKUP",
    UPDATE_BACKUP = "UPDATE_BACKUP",
    DELETE_BACKUP = "DELETE_BACKUP",

    NOTIFICATION_RECEIVED = "RECEIVED",
    NOTIFICATION_SENT = "SENT",
    NOTIFICATION_ACCEPT = "ACCEPT",
    NOTIFICATION_CANCEL = "CANCEL",
    NOTIFICATION_DELETED = "DELETED",
    NOTIFICATION_REJECT = "REJECT",
    NOTIFICATION_CHANGE_USER_ROLE_ALBUM = "CHANGE_USER_ROLE_ALBUM",
    NOTIFICATION_REMOVE_USER_ALBUM = "REMOVE_USER_ALBUM",
    
    NOTIFICATION_ALL = "ALL",
    NOTIFICATION_UPLOAD_IMAGE = "UPLOAD_IMAGE",
    NOTIFICATION_UPLOAD_VIDEO = "UPLOAD_VIDEO",
    NOTIFICATION_TRANSFER_OWNER = "TRANSFER_OWNER",
    NOTIFICATION_TRANSFER_OWNER_REJECT = "TRANSFER_OWNER_REJECT",
    NOTIFICATION_TRANSFER_OWNER_ACCEPT = "TRANSFER_OWNER_ACCEPT",


    NOTIFICATION_JOIN_REQUEST = "JOIN_REQUEST",
    NOTIFICATION_JOIN_APPROVED = "JOIN_APPROVED",
    NOTIFICATION_JOIN_REJECTED = "JOIN_REJECTED",
}